```{r}
library(gssr)
library(tidyverse)
# don't recommend getting single year -- not enough data
# gss21 <- gss_get_yr(2021)
# gss21["sexsex"]


```

```{r}
data(gss_all)
```

```{r}
gss_clean <- gss_all |>
  mutate(
    id = paste0(year, '_', id),
    sexnow = coalesce(sexnow, sexnow1),
    sexbirth = coalesce(sexbirth, sexbirth1),
    ) |>
  select(id, year, sex, sexnow, sexbirth, sexornt, sexsex, sexsex5)
```
```{r}

```


```{r}
# grab a subset of data, specifically
# all responses from years in which all
# required questions in {qns} are asked/
# have answers.
# Optionally, also filter to only entries
# with answers to all questions.
getSubsetWithAnswers <- function(qns, clean_na = FALSE) {
  years_all_asked <- gss_all |>
    gss_which_years(qns) |>
    na_if(FALSE) |>
    drop_na() |>
    pull(year)
  
  gss_all |>
    filter(year %in% years_all_asked) |>
    select(year, id, all_of(qns)) |>
    filter(across(qns, ~ !clean_na | !is.na(.)))
}
```

```{r}
# this dataset contains a whopping 1 intersex person,
# and only 12 who identify their SEXNOW as 3 [transgender].
# In fact, only 42 people identify their SEXBIRTH as different from SEXNOW.
getSubsetWithAnswers(c("sexnow", "sexbirth"), clean_na = T) |>
  ggplot(aes(x = as.factor(sexbirth), y = as.factor(sexnow))) +
  geom_bin2d()
```
```{r}
# Interesting...
gss_clean |> 
  filter(sexbirth != sexnow |
         sexnow != sex |
         sex != sexbirth) |> 
  select(id, sexbirth, sexnow, sex)
```

```{r}
gss_clean |>
  filter(!if_any(c(sexsex, sexnow, sexornt), is.na)) |>
  ggplot(aes(x = as_factor(sexsex), fill=as_factor(sexsex))) +
  geom_histogram(stat="count") +
  scale_fill_manual(values=c('blue', 'purple', 'red')) +
  theme(axis.text.x = element_blank()) +
  facet_grid(sexnow ~ sexornt,
             scales = "free_y")
```
```{r}
gss_clean |>
  filter(!if_any(c(sexsex5, sexnow, sexornt), is.na)) |>
  ggplot(aes(x = as_factor(sexsex5), fill=as_factor(sexsex5))) +
  geom_histogram(stat="count") +
  scale_fill_manual(values=c('blue', 'purple', 'red')) +
  #geom_text(stat="count", aes(label=..count..), position = position_stack(vjust=.5), color="black") +
  theme_bw() + 
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    panel.grid.major.x = element_blank()
    ) +
  facet_grid(sexornt ~ sexnow,
             scales = "free_y",
             labeller = label_wrap_gen(width = 16, multi_line = T)
             )
```

```{r}
# Well, let's see just /how/ flawed the data is.

subsetWith <- function(..) {
  gss_clean |>
    filter(!if_any(.., is.na))
}
```
```{r}
gender_counts <- subsetWith(c('sex', 'sexbirth', 'sexnow')) |>
  mutate(
    sex_changed = sexbirth != sexnow,
    sex_mismatch = sexbirth == sexnow & sexnow != sex,
    sex_coded_birth = sex == sexbirth,
    sex_coded_now = sex == sexnow
  ) |>
  count(sex, sexbirth, sexnow, sex_changed, sex_mismatch, sex_coded_birth, sex_coded_now) |>
  mutate(
  trans_miscoded = sex_changed & !sex_coded_now
  )

gender_counts |>
  ggplot(aes(x = as_factor(trans_miscoded), y = n, fill=trans_miscoded)) +
  geom_bar(stat = "identity") +
  labs(
    x = "Respondent-identified gender",
    y = "Interviewer-coded sex of respondent",
    fill = "Apparent misgendering?"
  ) +
   theme(
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank()
  ) +
  facet_grid(as_factor(sex) ~ as_factor(sexnow), scales="free_y", labeller = label_wrap_gen(width = 16, multi_line = T))

# gss_clean |> 
#   filter(!if_any(c(sex, sexbirth, sexnow), is.na)) |>
#   mutate(
#     sex_mismatch = 
#   )
#   group_by(year) |>
#   summarize()
#   ggplot(aes(x = factor(year)))
```
```{r}
gender_counts |>
  #filter(sexnow %in% c(1, 2)) |>
  ggplot(aes(x = sex_coded_now, y = n, fill = sex_coded_now)) +
  geom_bar(stat = "identity", position="dodge") +
  geom_text(aes(label=n, vjust="center")) +
  labs(
    x = "Assigned sex at birth (respondent-identified)",
    y = "Gender identity (respondent-identified)*",
    fill = "Reporter-indicated sex matches gender?"
  ) +
   theme(
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank()
  ) +
  #scale_fill_manual(values=c('blue', 'red')) + 
  facet_grid(as_factor(sexnow) ~ as_factor(sexbirth), scales="free_y", labeller = label_wrap_gen(width = 16, multi_line = T))
```
